### ISSUE TITLE
Demo seems broken

### ISSUE THREAD

**Issue by Zireael07** [Stehfyn/pathfinding#1]
I can add entities but that's all - only AStar environment option shows anything on screen, and entities happily pathfind across it anyway

**Comment by Stehfyn** [comment]
@Zireael07 Yeah this was for a homework assignment from back when I was in college that I never finished, decided to just take the L on the assignment since it was only worth like 2.5% of my grade... Anyway I have more recent stuff locally I can push if you're still inclined. Also this was my 2nd rust project ever, and written in less than a week during my senior year, so in truth I do not recommend this repository as a resource as it's definitely bad code.

For path planning and path tracking I recommend https://github.com/AtsushiSakai/PythonRobotics as it is relatively exhaustive of fundamental pathing algorithms.

**Comment by Stehfyn** [comment]
### **Ctrl + Left Click** to group select entities

https://github.com/user-attachments/assets/ec3eb18d-4c94-4924-86f7-0bed0b32b60b

@Zireael07
